src/Entity/Objet.php
<?php

namespace App\Entity;

use App\Repository\ObjetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ObjetRepository::class)
 */
class Objet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle_Objet;

    /**
     * @ORM\Column(type="date")
     */
    private $lastModif_Objet;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite_Objet = 0;




    /**
     * @ORM\ManyToOne(targetEntity=Inventaire::class, inversedBy="objets")
     * @ORM\JoinColumn(nullable=true)
     */
    private $Inventaire;

    /**
     * @ORM\ManyToOne(targetEntity=Appareil::class, inversedBy="objets")
     */
    private $Appareil;

    /**
     * @ORM\ManyToOne(targetEntity=Marque::class, inversedBy="objets")
     */
    private $Marque;

    /**
     * @ORM\ManyToOne(targetEntity=Modele::class, inversedBy="objets")
     */
    private $Modele;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numSerieObjet;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getLibelleObjet(): ?string
    {
        return $this->libelle_Objet;
    }

    public function setLibelleObjet(string $libelle_Objet): self
    {
        $this->libelle_Objet = $libelle_Objet;

        return $this;
    }

    public function getLastModifObjet(): ?\DateTimeInterface
    {
        return $this->lastModif_Objet;
    }

    public function setLastModifObjet(\DateTimeInterface $lastModif_Objet): self
    {
        $this->lastModif_Objet = $lastModif_Objet;

        return $this;
    }

    public function getQuantiteObjet(): ?int
    {
        return $this->quantite_Objet;
    }

    public function setQuantiteObjet(int $quantite_Objet): self
    {
        $this->quantite_Objet = $quantite_Objet;

        return $this;
    }

    public function decreaseQuantite(): self
    {
        $this->quantite_Objet--;
        return $this;
    }

    public function increaseQuantite(): self
    {
        $this->quantite_Objet++;
        return $this;
    }

    public function getInventaire(): ?Inventaire
    {
        return $this->Inventaire;
    }

    public function setInventaire(?Inventaire $Inventaire): self
    {
        $this->Inventaire = $Inventaire;

        return $this;
    }

    public function getAppareil(): ?Appareil
    {
        return $this->Appareil;
    }

    public function setAppareil(?Appareil $Appareil): self
    {
        $this->Appareil = $Appareil;

        return $this;
    }

    public function getMarque(): ?Marque
    {
        return $this->Marque;
    }

    public function setMarque(?Marque $Marque): self
    {
        $this->Marque = $Marque;

        return $this;
    }

    public function getModele(): ?Modele
    {
        return $this->Modele;
    }

    public function setModele(?Modele $Modele): self
    {
        $this->Modele = $Modele;

        return $this;
    }

    public function getNumSerieObjet(): ?string
    {
        return $this->numSerieObjet;
    }

    public function setNumSerieObjet(?string $numSerieObjet): self
    {
        $this->numSerieObjet = $numSerieObjet;

        return $this;
    }

}

src/Controller/Admin/ObjetController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Objet;
use App\Form\ObjetType;
use App\Model\FiltreObjet;
use App\Entity\Cputilisateur;
use App\Form\FiltreObjetType;
use App\Form\CputilisateurType;
use App\Repository\ObjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ObjetController extends AbstractController
{

    /**
     * @Route("/admin/objet/{id}/augmenter-quantite", name="admin_objets_increase_quantite")
     */    
    public function increaseQuantite(Objet $objet): RedirectResponse
    {
        $objet->increaseQuantite();
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('admin_objets');
    }


    /**
     * @Route("/admin/objet/{id}/diminuer-quantite", name="admin_objets_decrease_quantite")
     * @Route("/admin/cputilisateur/ajout", name="admin_cputilisateur_ajout", methods={"GET","POST"})
     */
    public function decreaseQuantite( Request $request, EntityManagerInterface $manager, Objet $objet)
    {
       
        $cputilisateur=new Cputilisateur();
        $form=$this->createForm(CputilisateurType::class, $cputilisateur);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $objet->decreaseQuantite();
            $this->getDoctrine()->getManager()->flush();
            $manager->persist($cputilisateur);
            $manager->flush();
            return $this->redirectToRoute('admin_cputilisateurs');
        }
        return $this->render('admin/cputilisateur/formAjoutCputilisateur.html.twig', [
            'formCputilisateur' => $form->createView()
        ]);
    }

    /**
     * @Route("/admin/objets", name="admin_objets", methods={"GET"})
     */
    public function listeObjets(ObjetRepository $repo, PaginatorInterface $paginator, Request $request)
    {
        $filtre=new FiltreObjet();
        $formFiltreObjet=$this->createForm(FiltreObjetType::class, $filtre);
        $formFiltreObjet->handleRequest($request);
        //dd($filtre);
        $objets = $paginator->paginate(
        $repo->listeObjetsCompletePaginee($filtre),
        $request->query->getInt('page', 1), 9
        );
        return $this->render('admin/objet/listeObjets.html.twig', [
            'lesObjets' => $objets,
            'formFiltreObjet'=>$formFiltreObjet->createView()
        ]);
    }

    /**
     * @Route("/admin/objet/ajout", name="admin_objet_ajout", methods={"GET","POST"})
     * @Route("/admin/objet/modif/{id}", name="admin_objet_modif", methods={"GET","POST"})
     */
    public function ajoutModifObjet(Objet $objet=null, Request $request, EntityManagerInterface $manager)
    {
        if($objet == null){
            $objet=new Objet();
            $mode="ajouté";
        }else{
            $mode="modifié";
        }
        $form=$this->createForm(ObjetType::class, $objet);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $manager->persist($objet);
            $manager->flush();
            $this->addFlash("success","Le Matériel Informatique a bien été $mode");
            return $this->redirectToRoute('admin_objets');
        }
        return $this->render('admin/objet/formAjoutModifObjet.html.twig', [
            'formObjet' => $form->createView()
            
        ]);
    }

    /**
     * @Route("/admin/objet/suppression/{id}", name="admin_objet_suppression", methods={"GET"})
     */
    public function suppressionObjet(Objet $objet, EntityManagerInterface $manager)
    {
        $manager->remove($objet);
        $manager->flush();
        $this->addFlash("success","Le Matériel Informatique a bien été supprimé");
        return $this->redirectToRoute('admin_objets');
    }
}

src/Controller/Utilisateur/ObjetControllerUtili.php
<?php

namespace App\Controller\Utilisateur;

use App\Entity\Objet;
use App\Form\ObjetType;
use App\Model\FiltreObjet;
use App\Entity\Cputilisateur;
use App\Form\FiltreObjetType;
use App\Form\CputilisateurType;
use App\Repository\ObjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ObjetControllerUtili extends AbstractController
{
    /**
     * @Route("/utilisateur/objet/{id}/augmenter-quantite", name="objet_increase_quantite")
     */    
    public function increaseQuantite(Objet $objet): RedirectResponse
    {
        $objet->increaseQuantite();
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('utilisateur_objets');
    }


    /**
     * @Route("/utilisateur/objet/{id}/diminuer-quantite", name="objet_decrease_quantite")
     * @Route("/admin/cputilisateur/ajout", name="admin_cputilisateur_ajout", methods={"GET","POST"})
     */
    public function decreaseQuantite( Request $request, EntityManagerInterface $manager, Objet $objet)
    {

        $cputilisateur=new Cputilisateur();
        $form=$this->createForm(CputilisateurType::class, $cputilisateur);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $objet->decreaseQuantite();
            $this->getDoctrine()->getManager()->flush();
            $manager->persist($cputilisateur);
            $manager->flush();
            return $this->redirectToRoute('admin_cputilisateurs');
        }
        return $this->render('admin/cputilisateur/formAjoutCputilisateur.html.twig', [
            'formCputilisateur' => $form->createView()
        ]);
    }

    /**
     * @Route("/utilisateur/objets", name="utilisateur_objets", methods={"GET"})
     */
    public function listeObjets(ObjetRepository $repo, PaginatorInterface $paginator, Request $request)
    {
        $filtre=new FiltreObjet();
        $formFiltreObjet=$this->createForm(FiltreObjetType::class, $filtre);
        $formFiltreObjet->handleRequest($request);
        //dd($filtre);
        $objets = $paginator->paginate(
        $repo->listeObjetsCompletePaginee($filtre),
        $request->query->getInt('page', 1), 9
        );
        return $this->render('utilisateur/objet/listeObjetsUtil.html.twig', [
            'lesObjets' => $objets,
            'formFiltreObjet'=>$formFiltreObjet->createView()
        ]);
    }

    /**
     * @Route("/utilisateur/objet/ajout", name="utilisateur_objet_ajout", methods={"GET","POST"})
     * @Route("/utilisateur/objet/modif/{id}", name="utilisateur_objet_modif", methods={"GET","POST"})
     */
    public function ajoutModifObjet(Objet $objet=null, Request $request, EntityManagerInterface $manager)
    {
        if($objet == null){
            $objet=new Objet();
            $mode="ajouté";
        }else{
            $mode="modifié";
        }
        $form=$this->createForm(ObjetType::class, $objet);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $manager->persist($objet);
            $manager->flush();
            $this->addFlash("success","Le Matériel Informatique a bien été $mode");
            return $this->redirectToRoute('utilisateur_objets');
        }
        return $this->render('utilisateur/objet/formAjoutModifObjetUtil.html.twig', [
            'formObjet' => $form->createView()
            
        ]);
    }

    /**
     * @Route("/utilisateur/objet/suppression/{id}", name="utilisateur_objet_suppression", methods={"GET"})
     */
    public function suppressionObjet(Objet $objet, EntityManagerInterface $manager)
    {
        $manager->remove($objet);
        $manager->flush();
        $this->addFlash("success","Le Matériel Informatique a bien été supprimé");
        return $this->redirectToRoute('utilisateur_objets');
    }
}

src/Controller/Utilisateur/TelControllerUtili.php
<?php

namespace App\Controller\Utilisateur;

use App\Entity\Tel;
use App\Form\TelType;
use App\Model\FiltreTel;
use App\Form\FiltreTelType;
use App\Entity\Cputilisateur;
use App\Form\CputilisateurType;
use App\Repository\TelRepository;
use App\Repository\ObjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TelControllerUtili extends AbstractController
{

    /**
     * @Route("/utilisateur/tel/{id}/augmenter-quantite", name="tel_increase_quantite")
     */    
    public function increaseQuantite(Tel $tel): RedirectResponse
    {
        $tel->increaseQuantite();
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('utilisateur_tels');
    }


    /**
     * @Route("/utilisateur/tel/{id}/diminuer-quantite", name="tel_decrease_quantite")
     * @Route("/admin/cputilisateur/ajout", name="admin_cputilisateur_ajout", methods={"GET","POST"})
     */
    public function decreaseQuantite(Tel $tel, Request $request, EntityManagerInterface $manager)
    {

        $cputilisateur=new Cputilisateur();
        $form=$this->createForm(CputilisateurType::class, $cputilisateur);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $tel->decreaseQuantite();
            $this->getDoctrine()->getManager()->flush();
            $manager->persist($cputilisateur);
            $manager->flush();
            return $this->redirectToRoute('admin_cputilisateurs');
        }
        return $this->render('admin/cputilisateur/formAjoutCputilisateur.html.twig', [
            'formCputilisateur' => $form->createView()
        ]);    }
    
    /**
     * @Route("/utilisateur/tels", name="utilisateur_tels", methods={"GET"})
     */
    public function listeTels(TelRepository $repo, PaginatorInterface $paginator, Request $request)
    {
        $filtre=new FiltreTel();
        $formFiltreTel=$this->createForm(FiltreTelType::class, $filtre);
        $formFiltreTel->handleRequest($request);
        //dd($filtre);
        $tels = $paginator->paginate(
        $repo->listeTelsCompletePaginee($filtre),
        $request->query->getInt('page', 1), 9
        );
        return $this->render('utilisateur/tel/listeTelsUtil.html.twig', [
            'lesTels' => $tels,
            'formFiltreTel'=>$formFiltreTel->createView()
        ]);
    }

    /**
     * @Route("/utilisateur/tel/ajout", name="utilisateur_tel_ajout", methods={"GET","POST"})
     * @Route("/utilisateur/tel/modif/{id}", name="utilisateur_tel_modif", methods={"GET","POST"})
     */
    public function ajoutModifTel(Tel $tel=null, Request $request, EntityManagerInterface $manager)
    {
        if($tel == null){
            $tel=new Tel();
            $mode="ajouté";
        }else{
            $mode="modifié";
        }
        $form=$this->createForm(TelType::class, $tel);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $manager->persist($tel);
            $manager->flush();
            $this->addFlash("success","Le Tel/Ipad a bien été $mode");
            return $this->redirectToRoute('utilisateur_tels');
        }
        return $this->render('utilisateur/tel/formAjoutModifTelUtil.html.twig', [
            'formTel' => $form->createView()
            
        ]);
    }

    /**
     * @Route("/utilisateur/tel/suppression/{id}", name="utilisateur_tel_suppression", methods={"GET"})
     */
    public function suppressionTel(Tel $tel, EntityManagerInterface $manager)
    {
        $manager->remove($tel);
        $manager->flush();
        $this->addFlash("success","Le Tel/Ipad a bien été supprimé");
        return $this->redirectToRoute('utilisateur_tels');
    }
}

templates/utilisateur/objet/formAjoutModifObjetUtil.html.twig
{% extends 'base.html.twig' %}

{% block title %}modif matériel infortique{% endblock %}

{% block body %}
<h2 class="text-center pt-2 ">
{% if (app.request.attributes.get('_route')=="utilisateur_objet_modif") %}
 Modification
 {% else %}
  Ajout
{% endif %}
d'un objet</h1>

{{form_start(formObjet,{'attr':{'novalidate':'novalidate'}})}}
{{form_row(formObjet.libelleObjet)}}
<div class="row">
  <div class="col">{{form_row(formObjet.appareil)}}</div>
  <div class="col">{{form_row(formObjet.marque)}}</div>
  <div class="col">{{form_row(formObjet.modele)}}</div>
</div>
{{form_row(formObjet.numSerieObjet)}}
{{form_row(formObjet.lastModifObjet)}}
{{form_row(formObjet.quantiteObjet)}}
<div class="row">
  <div class="col"><a href="{{path('utilisateur_objets')}} " class="btn btn-warning btn-block">Annuler</a></div>
  <div class="col"><input type="submit", class="btn btn-success btn-block" value=
  {% if (app.request.attributes.get('_route')=="utilisateur_objet_ajout") %}
  "Ajouter le matériel infortique"
  {% else %}
  "Modifier le matériel infortique"
  {% endif %}></div>
</div>

{{form_end(formObjet)}}
{% endblock %}

templates/utilisateur/objet/listeObjetsUtil.html.twig
{% extends 'base.html.twig' %}

{% block title %}gestion matériel informatique{% endblock %}

{% block body %}
<h2 class="text-center pt-2 ">Gestion du matériel informatique</h2>
{#<a href=" {{path('utilisateur_objet_ajout')}} " class="btn btn-success">Ajouter un objet</a>#}
<br>
{{ form_start(formFiltreObjet)}}
<div class="row">
  <div class="col-6">  {{ form_row(formFiltreObjet.nom)}}</div>
  <div class="col-2">  {{ form_row(formFiltreObjet.appareil)}}</div>
  <div class="col-2">  {{ form_row(formFiltreObjet.marque)}}</div>
  <div class="col-2">  {{ form_row(formFiltreObjet.modele)}}</div>
</div>
  <button type="submit" class ="btn btn-warning">Rechercher</button>
{{ form_end(formFiltreObjet)}}

<br>  
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col-1">ID du matériel informatique</th>
      <th scope="col-5">Libellé du matériel informatique</th>
      <th scope="col-2">Date d'ajout du matériel infortique</th>
      <th scope="col-2">Quantité du matériel informatique</th>
    </tr>
  </thead>
  

  <tbody>


        {% for leObjet in lesObjets %}
              {% if (leObjet.quantiteObjet == 0) %}
              <table class="table table-danger">
              {% else %}
              <table class="table table-hover">
              {% endif %}
         
            <tr>
            <td scope="col-1">{{leObjet.id}}</td>
            <td scope="col-7">
                <p class="d-flex flex-row">
                <div class="align-self-center badge badge-success"> {{leObjet.appareil.genreappareil}}</div>
                <div class="align-self-center badge badge-success"> {{leObjet.marque.nommarque}}</div>
                <div class="align-self-center badge badge-success"> {{leObjet.modele.nommodele}}</div>
                 <div class="align-self-center badge badge-success"> {{leObjet.modele.nommodele}}</div>
                 {% if (leObjet.numSerieObjet == true ) %}<div class="align-self-center badge badge-success">NUM SERIE : {{leObjet.numSerieObjet}}</div>
                 {% else %}
                 {% endif %}
            </p>
            {{leObjet.libelleObjet}}
            </p>
            </td>
           
            <td scope="col-1">{{leObjet.lastModifObjet|date("m/d/Y")}}</td>
            {#<td scope="col-1">{{leObjet.quantiteObjet}}</td>#}

<td scope="col-1">
           <div class="input-group input-group-sm justify-content-center">
             <a href="{{ path("objet_decrease_quantite", { 'id': leObjet.id})}}" class="btn btn-sm btn-outline-primary">
    <span class="fas fa-minus"></span>
     </a>
     <span class="input-group-text bg-white border-top border-bottom"> {{leObjet.quantiteObjet}}</span>   
    <a href="{{ path("objet_increase_quantite", { 'id': leObjet.id})}}" class="btn btn-sm btn-outline-primary">
      <span class="fas fa-plus"></span>
  </a>

  </div>
            </td>

            {#  <td class="col-2">
             <a href=" {{path('utilisateur_objet_modif', {'id': leObjet.id })}} " class="btn btn-primary"><i class="fas fa-pen"></i></a>
         <a class="btn btn-danger" 
            data-toggle="modal" 
            data-target="#modalSimple"
            data-titre="Suppression d'un objet"
            data-message="Etes vous sur de vouloir supprimer l'objet : {{ leObjet.libelleObjet }}"
            data-libelleBouton = "Supprimer l'objet"
            data-lien= " {{ path('utilisateur_objet_suppression', {'id': leObjet.id}) }}"
            ><i class="far fa-trash-alt"></i></a>
            </td> #} 
            </tr>
  
        {% endfor %}
</tbody>
</table>
      <div class="navigation mx-auto">
        {{ knp_pagination_render(lesObjets) }}
      </div>
{% endblock %}
{% block javascripts %}
  {% include "include/_modale.html.twig" %}
{% endblock %}