src/Entity/Tel.php
<?php

namespace App\Entity;

use App\Repository\TelRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TelRepository::class)
 */
class Tel
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle_Tel;

    /**
     * @ORM\Column(type="date")
     */
    private $lastModif_Tel;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite_Tel = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Inventaire::class, inversedBy="tels")
     */
    private $Inventaire;

    /**
     * @ORM\ManyToOne(targetEntity=Appareil::class, inversedBy="tels")
     */
    private $Appareil;

    /**
     * @ORM\ManyToOne(targetEntity=Marque::class, inversedBy="tels")
     */
    private $Marque;

    /**
     * @ORM\ManyToOne(targetEntity=Modele::class, inversedBy="tels")
     */
    private $Modele;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numSerie;

    /**
     * @ORM\ManyToOne(targetEntity=Cputilisateur::class, inversedBy="tels")
     */
    private $Cputilisateur;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getLibelleTel(): ?string
    {
        return $this->libelle_Tel;
    }

    public function setLibelleTel(string $libelle_Tel): self
    {
        $this->libelle_Tel = $libelle_Tel;

        return $this;
    }

    public function getLastModifTel(): ?\DateTimeInterface
    {
        return $this->lastModif_Tel;
    }

    public function setLastModifTel(\DateTimeInterface $lastModif_Tel): self
    {
        $this->lastModif_Tel = $lastModif_Tel;

        return $this;
    }

    public function getQuantiteTel(): ?int
    {
        return $this->quantite_Tel;
    }

    public function setQuantiteTel(int $quantite_Tel): self
    {
        $this->quantite_Tel = $quantite_Tel;

        return $this;
    }

    
    public function decreaseQuantite(): self
    {
        $this->quantite_Tel--;
        return $this;
    }

    public function increaseQuantite(): self
    {
        $this->quantite_Tel++;
        return $this;
    }

    public function getInventaire(): ?Inventaire
    {
        return $this->Inventaire;
    }

    public function setInventaire(?Inventaire $Inventaire): self
    {
        $this->Inventaire = $Inventaire;

        return $this;
    }

    public function getAppareil(): ?Appareil
    {
        return $this->Appareil;
    }

    public function setAppareil(?Appareil $Appareil): self
    {
        $this->Appareil = $Appareil;

        return $this;
    }

    public function getMarque(): ?Marque
    {
        return $this->Marque;
    }

    public function setMarque(?Marque $Marque): self
    {
        $this->Marque = $Marque;

        return $this;
    }

    public function getModele(): ?Modele
    {
        return $this->Modele;
    }

    public function setModele(?Modele $Modele): self
    {
        $this->Modele = $Modele;

        return $this;
    }

    public function getNumSerie(): ?string
    {
        return $this->numSerie;
    }

    public function setNumSerie(?string $numSerie): self
    {
        $this->numSerie = $numSerie;

        return $this;
    }

    public function getCputilisateur(): ?Cputilisateur
    {
        return $this->Cputilisateur;
    }

    public function setCputilisateur(?Cputilisateur $Cputilisateur): self
    {
        $this->Cputilisateur = $Cputilisateur;

        return $this;
    }

}

src/Controller/Admin/TelController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Tel;
use App\Form\TelType;
use App\Model\FiltreTel;
use App\Form\FiltreTelType;
use App\Entity\Cputilisateur;
use App\Form\CputilisateurType;
use App\Form\TelAttributionType;
use App\Repository\TelRepository;
use App\Repository\ObjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TelController extends AbstractController
{

        /**
     * @Route("/admin/tel/{id}/augmenter-quantite", name="admin_tels_increase_quantite")
     */    
    public function increaseQuantite(Tel $tel): RedirectResponse
    {
        $tel->increaseQuantite();
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('admin_tels');
    }


    /**
     * @Route("/admin/tel/{id}/diminuer-quantite", name="admin_tels_decrease_quantite")
     * @Route("/admin/cputilisateur/ajout", name="admin_cputilisateur_ajout", methods={"GET","POST"})
     */

    public function decreaseQuantite(Tel $tel=null, Request $request, EntityManagerInterface $manager)
    {
        
        $cputilisateur=new Cputilisateur();
        $form=$this->createForm(CputilisateurType::class, $cputilisateur);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $tel->decreaseQuantite();
            $this->getDoctrine()->getManager()->flush();
            $manager->persist($cputilisateur);
            $manager->flush();
            return $this->redirectToRoute('admin_cputilisateurs');
        }
        return $this->render('admin/cputilisateur/formAjoutCputilisateur.html.twig', [
            'formCputilisateur' => $form->createView()
        ]);
    }

    /**
     * @Route("/admin/tels", name="admin_tels", methods={"GET"})
     */
    public function listeTels(TelRepository $repo, PaginatorInterface $paginator, Request $request)
    {
        $filtre=new FiltreTel();
        $formFiltreTel=$this->createForm(FiltreTelType::class, $filtre);
        $formFiltreTel->handleRequest($request);
        //dd($filtre);
        $tels = $paginator->paginate(
        $repo->listeTelsCompletePaginee($filtre),
        $request->query->getInt('page', 1), 9
        );
        return $this->render('admin/tel/listeTels.html.twig', [
            'lesTels' => $tels,
            'formFiltreTel'=>$formFiltreTel->createView()
        ]);
    }

    /**
     * @Route("/admin/tel/ajout", name="admin_tel_ajout", methods={"GET","POST"})
     * @Route("/admin/tel/modif/{id}", name="admin_tel_modif", methods={"GET","POST"})
     */
    public function ajoutModifTel(Tel $tel=null, Request $request, EntityManagerInterface $manager)
    {
        if($tel == null){
            $tel=new Tel();
            $mode="ajouté";
        }else{
            $mode="modifié";
        }
        $form=$this->createForm(TelType::class, $tel);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $manager->persist($tel);
            $manager->flush();
            $this->addFlash("success","Le Tel/Ipad a bien été $mode");
            return $this->redirectToRoute('admin_tels');
        }
        return $this->render('admin/tel/formAjoutModifTel.html.twig', [
            'formTel' => $form->createView()
            
        ]);
    }

    /**
     * @Route("/admin/tel/suppression/{id}", name="admin_tel_suppression", methods={"GET"})
     */
    public function suppressionTel(Tel $tel, EntityManagerInterface $manager)
    {
        $manager->remove($tel);
        $manager->flush();
        $this->addFlash("success","Le Tel/Ipad a bien été supprimé");
        return $this->redirectToRoute('admin_tels');
    }
}

src/Controller/Utilisateur/ObjetControllerUtili.php
<?php

namespace App\Controller\Utilisateur;

use App\Entity\Objet;
use App\Form\ObjetType;
use App\Model\FiltreObjet;
use App\Entity\Cputilisateur;
use App\Form\FiltreObjetType;
use App\Form\CputilisateurType;
use App\Repository\ObjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ObjetControllerUtili extends AbstractController
{
    /**
     * @Route("/utilisateur/objet/{id}/augmenter-quantite", name="objet_increase_quantite")
     */    
    public function increaseQuantite(Objet $objet): RedirectResponse
    {
        $objet->increaseQuantite();
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('utilisateur_objets');
    }


    /**
     * @Route("/utilisateur/objet/{id}/diminuer-quantite", name="objet_decrease_quantite")
     * @Route("/admin/cputilisateur/ajout", name="admin_cputilisateur_ajout", methods={"GET","POST"})
     */
    public function decreaseQuantite( Request $request, EntityManagerInterface $manager, Objet $objet)
    {

        $cputilisateur=new Cputilisateur();
        $form=$this->createForm(CputilisateurType::class, $cputilisateur);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $objet->decreaseQuantite();
            $this->getDoctrine()->getManager()->flush();
            $manager->persist($cputilisateur);
            $manager->flush();
            return $this->redirectToRoute('admin_cputilisateurs');
        }
        return $this->render('admin/cputilisateur/formAjoutCputilisateur.html.twig', [
            'formCputilisateur' => $form->createView()
        ]);
    }

    /**
     * @Route("/utilisateur/objets", name="utilisateur_objets", methods={"GET"})
     */
    public function listeObjets(ObjetRepository $repo, PaginatorInterface $paginator, Request $request)
    {
        $filtre=new FiltreObjet();
        $formFiltreObjet=$this->createForm(FiltreObjetType::class, $filtre);
        $formFiltreObjet->handleRequest($request);
        //dd($filtre);
        $objets = $paginator->paginate(
        $repo->listeObjetsCompletePaginee($filtre),
        $request->query->getInt('page', 1), 9
        );
        return $this->render('utilisateur/objet/listeObjetsUtil.html.twig', [
            'lesObjets' => $objets,
            'formFiltreObjet'=>$formFiltreObjet->createView()
        ]);
    }

    /**
     * @Route("/utilisateur/objet/ajout", name="utilisateur_objet_ajout", methods={"GET","POST"})
     * @Route("/utilisateur/objet/modif/{id}", name="utilisateur_objet_modif", methods={"GET","POST"})
     */
    public function ajoutModifObjet(Objet $objet=null, Request $request, EntityManagerInterface $manager)
    {
        if($objet == null){
            $objet=new Objet();
            $mode="ajouté";
        }else{
            $mode="modifié";
        }
        $form=$this->createForm(ObjetType::class, $objet);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $manager->persist($objet);
            $manager->flush();
            $this->addFlash("success","Le Matériel Informatique a bien été $mode");
            return $this->redirectToRoute('utilisateur_objets');
        }
        return $this->render('utilisateur/objet/formAjoutModifObjetUtil.html.twig', [
            'formObjet' => $form->createView()
            
        ]);
    }

    /**
     * @Route("/utilisateur/objet/suppression/{id}", name="utilisateur_objet_suppression", methods={"GET"})
     */
    public function suppressionObjet(Objet $objet, EntityManagerInterface $manager)
    {
        $manager->remove($objet);
        $manager->flush();
        $this->addFlash("success","Le Matériel Informatique a bien été supprimé");
        return $this->redirectToRoute('utilisateur_objets');
    }
}

src/Controller/Utilisateur/TelControllerUtili.php
<?php

namespace App\Controller\Utilisateur;

use App\Entity\Tel;
use App\Form\TelType;
use App\Model\FiltreTel;
use App\Form\FiltreTelType;
use App\Entity\Cputilisateur;
use App\Form\CputilisateurType;
use App\Repository\TelRepository;
use App\Repository\ObjetRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class TelControllerUtili extends AbstractController
{

    /**
     * @Route("/utilisateur/tel/{id}/augmenter-quantite", name="tel_increase_quantite")
     */    
    public function increaseQuantite(Tel $tel): RedirectResponse
    {
        $tel->increaseQuantite();
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('utilisateur_tels');
    }


    /**
     * @Route("/utilisateur/tel/{id}/diminuer-quantite", name="tel_decrease_quantite")
     * @Route("/admin/cputilisateur/ajout", name="admin_cputilisateur_ajout", methods={"GET","POST"})
     */
    public function decreaseQuantite(Tel $tel, Request $request, EntityManagerInterface $manager)
    {

        $cputilisateur=new Cputilisateur();
        $form=$this->createForm(CputilisateurType::class, $cputilisateur);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $tel->decreaseQuantite();
            $this->getDoctrine()->getManager()->flush();
            $manager->persist($cputilisateur);
            $manager->flush();
            return $this->redirectToRoute('admin_cputilisateurs');
        }
        return $this->render('admin/cputilisateur/formAjoutCputilisateur.html.twig', [
            'formCputilisateur' => $form->createView()
        ]);    }
    
    /**
     * @Route("/utilisateur/tels", name="utilisateur_tels", methods={"GET"})
     */
    public function listeTels(TelRepository $repo, PaginatorInterface $paginator, Request $request)
    {
        $filtre=new FiltreTel();
        $formFiltreTel=$this->createForm(FiltreTelType::class, $filtre);
        $formFiltreTel->handleRequest($request);
        //dd($filtre);
        $tels = $paginator->paginate(
        $repo->listeTelsCompletePaginee($filtre),
        $request->query->getInt('page', 1), 9
        );
        return $this->render('utilisateur/tel/listeTelsUtil.html.twig', [
            'lesTels' => $tels,
            'formFiltreTel'=>$formFiltreTel->createView()
        ]);
    }

    /**
     * @Route("/utilisateur/tel/ajout", name="utilisateur_tel_ajout", methods={"GET","POST"})
     * @Route("/utilisateur/tel/modif/{id}", name="utilisateur_tel_modif", methods={"GET","POST"})
     */
    public function ajoutModifTel(Tel $tel=null, Request $request, EntityManagerInterface $manager)
    {
        if($tel == null){
            $tel=new Tel();
            $mode="ajouté";
        }else{
            $mode="modifié";
        }
        $form=$this->createForm(TelType::class, $tel);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid() )
        {
            $manager->persist($tel);
            $manager->flush();
            $this->addFlash("success","Le Tel/Ipad a bien été $mode");
            return $this->redirectToRoute('utilisateur_tels');
        }
        return $this->render('utilisateur/tel/formAjoutModifTelUtil.html.twig', [
            'formTel' => $form->createView()
            
        ]);
    }

    /**
     * @Route("/utilisateur/tel/suppression/{id}", name="utilisateur_tel_suppression", methods={"GET"})
     */
    public function suppressionTel(Tel $tel, EntityManagerInterface $manager)
    {
        $manager->remove($tel);
        $manager->flush();
        $this->addFlash("success","Le Tel/Ipad a bien été supprimé");
        return $this->redirectToRoute('utilisateur_tels');
    }
}

templates/utilisateur/tel/formAjoutModifTelUtil.html.twig
{% extends 'base.html.twig' %}

{% block title %}modif objet{% endblock %}

{% block body %}
<h2 class="text-center pt-2 ">
{% if (app.request.attributes.get('_route')=="utilisateur_tel_modif") %}
   Modification
{% else %}
  Ajout
{% endif %}
d'un Tel</h1>

{{form_start(formTel,{'attr':{'novalidate':'novalidate'}})}}

{{form_row(formTel.libelleTel)}}
<div class="row">
  <div class="col">{{form_row(formTel.appareil)}}</div>
  <div class="col">{{form_row(formTel.marque)}}</div>
  <div class="col">{{form_row(formTel.modele)}}</div>
</div>
{{form_row(formTel.numSerie)}}
{{form_row(formTel.lastModifTel)}}
{{form_row(formTel.quantiteTel)}}

<div class="row">
  <div class="col"><a href="{{path('utilisateur_tels')}} " class="btn btn-warning btn-block">Annuler</a></div>
  <div class="col"><input type="submit", class="btn btn-success btn-block" value=
  {% if (app.request.attributes.get('_route')=="utilisateur_tel_ajout") %}
  "Ajouter le tel"
  {% else %}
  "Modifier le tel"
  {% endif %}></div>
</div>



{{form_end(formTel)}}
{% endblock %}

templates/utilisateur/tel/listeTelsUtil.html.twig
{% extends 'base.html.twig' %}

{% block title %}gestion Téléphone/Ipad{% endblock %}

{% block body %}
<h2 class="text-center pt-2 ">Gestion des Téléphones/Ipads</h2>
{#<a href=" {{path('utilisateur_tel_ajout')}} " class="btn btn-success">Ajouter un tel</a>#}
<br>
{{ form_start(formFiltreTel)}}
<div class="row">
  <div class="col-6">  {{ form_row(formFiltreTel.nom)}}</div>
  <div class="col-2">  {{ form_row(formFiltreTel.appareil)}}</div>
  <div class="col-2">  {{ form_row(formFiltreTel.marque)}}</div>
  <div class="col-2">  {{ form_row(formFiltreTel.modele)}}</div>
</div>
  <button type="submit" class ="btn btn-warning">Rechercher</button>
{{ form_end(formFiltreTel)}}<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col-1"> ID du Téléphone/Ipad</th>
      <th scope="col-5">Libellé du Téléphone/Ipad</th>
      <th scope="col-2">Date d'ajout du Téléphone/Ipad</th>
      <th scope="col-2">Quantité du Téléphone/Ipad</th>
    </tr>
  </thead>
  
<br>
  <tbody>
        {% for leTel in lesTels %}
        {% if (leTel.quantiteTel == 0) %}
              <table class="table table-danger">
              {% else %}
              <table class="table table-hover">
              {% endif %}

            <tr>
            <td scope="col-1">{{leTel.id}}</td>
            <td scope="col-7">      <p class="d-flex flex-row">
                <div class="align-self-center badge badge-success"> {{leTel.appareil.genreappareil}}</div>
                <div class="align-self-center badge badge-success"> {{leTel.marque.nommarque}}</div>
                <div class="align-self-center badge badge-success"> {{leTel.modele.nommodele}}</div>
                 {% if (leTel.numSerie == true ) %}<div class="align-self-center badge badge-success">NUM SERIE : {{leTel.numSerie}}</div>
                 {% else %}
                 {% endif %}
            </p>
            <p>
            {{leTel.libelleTel}}
            </p>
            </td>
            <td scope="col-1">{{leTel.lastModifTel|date("m/d/Y")}}</td>



<td scope="col-1">
           <div class="input-group input-group-sm justify-content-center">
             <a href="{{ path("tel_decrease_quantite", { 'id': leTel.id})}}" class="btn btn-sm btn-outline-primary">
    <span class="fas fa-minus"></span>
     </a>
     <span class="input-group-text bg-white border-top border-bottom"> {{leTel.quantiteTel}}</span>   
    <a href="{{ path("tel_increase_quantite", { 'id': leTel.id})}}" class="btn btn-sm btn-outline-primary">
      <span class="fas fa-plus"></span>
  </a>

  </div>
            </td>


            {#<td class="col-2">
            <a href=" {{path('utilisateur_tel_modif', {'id': leTel.id })}} " class="btn btn-primary"><i class="fas fa-pen"></i></a>
           <a class="btn btn-danger" 
            data-toggle="modal" 
            data-target="#modalSimple"
            data-titre="Suppression d'un tel"
            data-message="Etes vous sur de vouloir supprimer le tel : {{ leTel.libelleTel }}"
            data-libelleBouton = "Supprimer le tel"
            data-lien= " {{ path('utilisateur_tel_suppression', {'id': leTel.id}) }}"
            ><i class="far fa-trash-alt"></i></a>
            </td>#}
            </tr>
        {% endfor %}
</tbody>
</table>
      <div class="navigation mx-auto">
        {{ knp_pagination_render(lesTels) }}
      </div>
{% endblock %}
{% block javascripts %}
  {% include "include/_modale.html.twig" %}
{% endblock %}